<?php

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-select-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-select-builder bitrix.main.historydto

declare(strict_types=1);

namespace Bitrix24\SDK\Services\Main\UserHistory\Service;

use Bitrix24\SDK\Services\AbstractSelectBuilder;

class UserHistorySelectBuilder extends AbstractSelectBuilder
{
    public function __construct()
    {
        $this->select[] = 'id';
    }

    public function dateInsert(): self
    {
        $this->select[] = 'dateInsert';
        return $this;
    }

    public function eventType(): self
    {
        $this->select[] = 'eventType';
        return $this;
    }

    public function field(): self
    {
        $this->select[] = 'field';
        return $this;
    }

    public function remoteAddr(): self
    {
        $this->select[] = 'remoteAddr';
        return $this;
    }

    public function requestUri(): self
    {
        $this->select[] = 'requestUri';
        return $this;
    }

    public function updatedById(): self
    {
        $this->select[] = 'updatedById';
        return $this;
    }

    public function userAgent(): self
    {
        $this->select[] = 'userAgent';
        return $this;
    }

    public function userId(): self
    {
        $this->select[] = 'userId';
        return $this;
    }

}
