<?php

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-select-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-select-builder bitrix.main.historyfielddto

declare(strict_types=1);

namespace Bitrix24\SDK\Services\Main\UserHistoryChange\Service;

use Bitrix24\SDK\Services\AbstractSelectBuilder;

class UserHistoryChangeSelectBuilder extends AbstractSelectBuilder
{
    public function __construct()
    {
        $this->select[] = 'id';
    }

    public function data(): self
    {
        $this->select[] = 'data';
        return $this;
    }

    public function field(): self
    {
        $this->select[] = 'field';
        return $this;
    }

    public function historyId(): self
    {
        $this->select[] = 'historyId';
        return $this;
    }

}
