<?php

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-select-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-select-builder bitrix.note.collectionitemdto

declare(strict_types=1);

namespace Bitrix24\SDK\Services\Note\Collection\Service;

use Bitrix24\SDK\Services\AbstractSelectBuilder;

class CollectionSelectBuilder extends AbstractSelectBuilder
{
    public function __construct()
    {
        $this->select[] = 'id';
    }

    public function createdAt(): self
    {
        $this->select[] = 'createdAt';
        return $this;
    }

    public function createdBy(): self
    {
        $this->select[] = 'createdBy';
        return $this;
    }

    public function name(): self
    {
        $this->select[] = 'name';
        return $this;
    }

    public function policyLevel(): self
    {
        $this->select[] = 'policyLevel';
        return $this;
    }

    public function position(): self
    {
        $this->select[] = 'position';
        return $this;
    }

    public function updatedAt(): self
    {
        $this->select[] = 'updatedAt';
        return $this;
    }

    public function updatedBy(): self
    {
        $this->select[] = 'updatedBy';
        return $this;
    }

}
