<?php

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-select-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-select-builder bitrix.call.followupdto

declare(strict_types=1);

namespace Bitrix24\SDK\Services\Telephony\FollowUp\Service;

use Bitrix24\SDK\Services\AbstractSelectBuilder;

class FollowUpSelectBuilder extends AbstractSelectBuilder
{
    public function callId(): self
    {
        $this->select[] = 'callId';
        return $this;
    }

    public function callType(): self
    {
        $this->select[] = 'callType';
        return $this;
    }

    public function createdAt(): self
    {
        $this->select[] = 'createdAt';
        return $this;
    }

    public function durationSeconds(): self
    {
        $this->select[] = 'durationSeconds';
        return $this;
    }

    public function endDate(): self
    {
        $this->select[] = 'endDate';
        return $this;
    }

    public function evaluation(): self
    {
        $this->select = array_merge($this->select, ['evaluation.calendar', 'evaluation.criteria', 'evaluation.efficiencyValue']);
        return $this;
    }

    public function initiatorId(): self
    {
        $this->select[] = 'initiatorId';
        return $this;
    }

    public function insights(): self
    {
        $this->select = array_merge($this->select, ['insights.areasOfResponsibility', 'insights.engagementLevel', 'insights.finalRecommendations', 'insights.meetingStrengths', 'insights.meetingWeaknesses', 'insights.speakerAnalysis', 'insights.speakerEvaluationAvailable', 'insights.speechStyleInfluence']);
        return $this;
    }

    public function language(): self
    {
        $this->select[] = 'language';
        return $this;
    }

    public function outcomes(): self
    {
        $this->select[] = 'outcomes';
        return $this;
    }

    public function overview(): self
    {
        $this->select = array_merge($this->select, ['overview.actionItems', 'overview.agenda', 'overview.agreements', 'overview.detailedTakeaways', 'overview.meetingType', 'overview.meetings', 'overview.topic']);
        return $this;
    }

    public function participants(): self
    {
        $this->select[] = 'participants';
        return $this;
    }

    public function startDate(): self
    {
        $this->select[] = 'startDate';
        return $this;
    }

    public function summary(): self
    {
        $this->select[] = 'summary';
        return $this;
    }

    public function tracks(): self
    {
        $this->select[] = 'tracks';
        return $this;
    }

    public function transcription(): self
    {
        $this->select = array_merge($this->select, ['transcription.language', 'transcription.segments']);
        return $this;
    }

    public function uuid(): self
    {
        $this->select[] = 'uuid';
        return $this;
    }

    public function version(): self
    {
        $this->select[] = 'version';
        return $this;
    }
}
