<?php

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-select-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-select-builder bitrix.timeman.recorddto

declare(strict_types=1);

namespace Bitrix24\SDK\Services\Timeman\Record\Service;

use Bitrix24\SDK\Services\AbstractSelectBuilder;

class RecordSelectBuilder extends AbstractSelectBuilder
{
    public function __construct()
    {
        $this->select[] = 'id';
    }

    public function breakLength(): self
    {
        $this->select[] = 'breakLength';
        return $this;
    }

    public function duration(): self
    {
        $this->select[] = 'duration';
        return $this;
    }

    public function endTime(): self
    {
        $this->select[] = 'endTime';
        return $this;
    }

    public function isApproved(): self
    {
        $this->select[] = 'isApproved';
        return $this;
    }

    public function startTime(): self
    {
        $this->select[] = 'startTime';
        return $this;
    }

    public function userId(): self
    {
        $this->select[] = 'userId';
        return $this;
    }

}
