<?php
/**
 * @var string $namespace
 * @var string $className
 * @var string $operationPath
 * @var array<string, string> $phpTypedFields fieldName → phpType
 */
?>
<?= "<?php\n" ?>

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-item-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-item-builder <?= $operationPath . "\n\n" ?>
declare(strict_types=1);

namespace <?= $namespace ?>;

use Bitrix24\SDK\Services\AbstractItemBuilder;

class <?= $className ?> extends AbstractItemBuilder
{
<?php foreach ($phpTypedFields as $fieldName => $phpType): ?>
    public function <?= $fieldName ?>(<?= $phpType ?> $<?= $fieldName ?>): self
    {
        $this->fields['<?= $fieldName ?>'] = $<?= $fieldName ?>;
        return $this;
    }

<?php endforeach ?>}
