<?php
/**
 * @var string $namespace
 * @var string $className
 * @var list<array{name: string, phpType: string, required: bool, nullable: bool, description: string|null}> $phpDocFields
 * @var bool $needsCarbon
 * @var string $sourceName
 */
?>
<?= "<?php\n" ?>

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:result-item-generator command.
<?= $sourceName !== '' ? '// Source: ' . $sourceName . "\n" : '' ?>declare(strict_types=1);

namespace <?= $namespace ?>;

use Bitrix24\SDK\Core\Result\AbstractAnnotatedItem;
<?php if ($needsCarbon): ?>
use Carbon\CarbonImmutable;
<?php endif; ?>

/**
<?php foreach ($phpDocFields as $field): ?>
 * @property-read <?= $field['phpType'] ?> $<?= $field['name'] . "\n" ?>
<?php endforeach; ?>
 */
class <?= $className ?> extends AbstractAnnotatedItem
{
}
