<?php
/**
 * @var string $namespace
 * @var string $className
 * @var string $entityKey
 * @var array<string, list<string>> $groups
 */
?>
<?= "<?php\n" ?>

/**
 * This file is part of the bitrix24-php-sdk package.
 *
 * © Maksim Mesilov <mesilov.maxim@gmail.com>
 *
 * For the full copyright and license information, please view the MIT-LICENSE.txt
 * file that was distributed with this source code.
 */

// This class was automatically generated by the b24-dev:generate-select-builder command.
// Source: OpenAPI schema snapshot (docs/open-api/openapi.json).
// To regenerate, run: php bin/console b24-dev:generate-select-builder <?= $entityKey . "\n\n" ?>
declare(strict_types=1);

namespace <?= $namespace ?>;

use Bitrix24\SDK\Services\AbstractSelectBuilder;

class <?= $className ?> extends AbstractSelectBuilder
{
    public function __construct()
    {
        $this->select[] = 'id';
    }

<?php foreach ($groups as $prefix => $fields): ?>
<?php if (count($fields) === 1): ?>
    public function <?= $prefix ?>(): self
    {
        $this->select[] = '<?= $prefix ?>';
        return $this;
    }

<?php else: ?>
    public function <?= $prefix ?>(): self
    {
        $this->select = array_merge($this->select, [<?= implode(', ', array_map(static fn(string $f): string => "'{$f}'", $fields)) ?>]);
        return $this;
    }

<?php endif ?>
<?php endforeach ?>}
