name: "Allowed licenses checks"
on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: "composer-license-checker"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build Docker image"
        run: docker-compose build

      - name: "Install dependencies"
        run: make composer-install

      - name: "composer-license-checker"
        run: make lint-allowed-licenses

      - name: "is allowed licenses check succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ allowed licenses check pass, congratulations!'

      - name: "is allowed licenses check failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ allowed licenses check failed (╯°益°)╯彡┻━┻'
