name: "PhpCsFixer lint checks"
on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: "PhpCsFixer"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build Docker image"
        run: docker-compose build

      - name: "Install dependencies"
        run: make composer-install

      - name: "PhpCsFixer"
        run: make lint-cs-fixer

      - name: "is PhpCsFixer check succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ PhpCsFixer check pass, congratulations!'

      - name: "is PhpCsFixer check failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ PhpCsFixer check failed (╯°益°)╯彡┻━┻'
