name: "PHPStan lint checks"
on:
  push:
  pull_request:

jobs:
  static-analysis:
    name: "PHPStan"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build Docker image"
        run: docker compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g)

      - name: "Install dependencies"
        run: make composer-install

      - name: "PHPStan"
        run: make lint-phpstan

      - name: "is PHPStan check succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ PHPStan check pass, congratulations!'

      - name: "is PHPStan check failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ PHPStan check failed (╯°益°)╯彡┻━┻'
