name: "Rector lint checks"
on:
  push:
  pull_request:

jobs:
  tests:
    name: "Rector lint checks"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build Docker image"
        run: docker compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g)

      - name: "Install dependencies"
        run: make composer-install

      - name: "run Rector"
        run: make lint-rector

      - name: "is Rector check succeeded"
        if: ${{ success() }}
        run: |
          echo '✅ Rector check pass, congratulations!'

      - name: "is Rector check failed"
        if: ${{ failure() }}
        run: |
          echo '::error:: ❗️ Rector check failed (╯°益°)╯彡┻━┻'
